version: '3'
services:
    microSaver:
      build: ./microSaver
      image: saver
      ports:
        - 8080:8080
    
    db:
      image: mongo:latest
      container_name: "mongodb"
      restart: always
      ports:
        - 27017:27017
      volumes:
        - ./db:/data/db
    

    
    microServes:
      build: ./microServes
      image: serves
      restart: always
      ports:
        - 8090:8090

    microSender:
      build: ./microSender
      image: sender